### ISSUE TITLE
Can you publish a release with all the newest functionalities?

### ISSUE THREAD

**Issue by itssosh** [shysaur/PaintTheDesktop#2]
-

**Comment by shysaur** [comment]
I'd very much like to, but there is currently a bug that is nagging me and I do not know how to solve yet. Namely, presentation, PDF and freeform drawing windows sometimes become key when activating the hidden screen paint windows. 

This bug is not easy to reproduce which makes it even worse because it can cause havoc during a live presentation (which is what I use this tool for) completely at random. At the moment I'm working around the issue by having a separate instance of the app with the screen painting windows hacked away.

I'm looking at implementing a separate process just for handling screen paint windows to solve the issue but that will require quite a bit of refactoring and I don't have much time for it at the moment.

**Comment by shysaur** [comment]
Well I decided I don't care about that bug, so here's a new version finally!
